# Source:
# https://github.com/solana-labs/solana-accountsdb-plugin-postgres/blob/master/.github/workflows/test.yml

on:
  push:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  SCCACHE_CACHE_SIZE: "1G"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # The toolchain action should definitely be run before the cache action
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.70"
          components: rustfmt, clippy
          cache: true
          # avoid the default "-D warnings" which thrashes cache
          rustflags: ""

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3


      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      # https://blog.arriven.wtf/posts/rust-ci-cache/
      - uses: Swatinem/rust-cache@v2
        with:
          # will be covered by sscache
          cache-targets: false
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build 1
        run: |
          cargo build --locked --all-targets

