name: Publish Docker Image to GHCR

on:
  push:
  workflow_dispatch:

env:
  IMAGE: lite-rpc
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Lite RPC (branch 'groovie/ping-thing-client')
        uses: actions/checkout@v4
        with:
          repository: 'grooviegermanikus/lite-rpc.git'
          ref: 'groovie/ping-thing-client'
          path: 'lite-rpc'

      - name: Use docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          buildkitd-flags: --debug

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the base image, leveraging layer caching
      - name: Build and Push Base Image
        uses: docker/build-push-action@v2
        with:
          file: ./bench-to-flyio/Dockerfile
          context: lite-rpc
          push: true
          tags: |
            ${{ env.REGISTRY }}/grooviegermanikus/${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
